apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: netapp-api-exporter
  name: netapp-api-exporter
  namespace: pgo-monitoring
spec:
  port:
    targetPort: metrics
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: netapp-api-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netapp-api-exporter
  name: netapp-api-exporter
  namespace: pgo-monitoring
spec:
  ports:
    - name: metrics
      port: 9108
      protocol: TCP
      targetPort: 9108
  selector:
    app: netapp-api-exporter
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: netapp-api-exporter
  name: netapp-api-exporter
  namespace: pgo-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netapp-api-exporter
  template:
    metadata:
      labels:
        app: netapp-api-exporter
    spec:
      containers:
        - args:
            - '-c'
            - /conf/netapp_filers.yaml
          image: >-
            docker-registry.default.svc:5000/pgo-monitoring/netapp-api-exporter:latest
          name: netapp-api-exporter
          ports:
            - containerPort: 9108
              protocol: TCP
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /conf
              name: secret-netapp-filers
              readOnly: true
      volumes:
        - name: secret-netapp-filers
          secret:
            defaultMode: 420
            items:
              - key: netapp_filers.yaml
                path: netapp_filers.yaml
            secretName: netappfilers
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - netapp-api-exporter
        from:
          kind: ImageStreamTag
          name: 'netapp-api-exporter:latest'
          namespace: pgo-monitoring
      type: ImageChange
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: netapp-api-exporter
  name: netapp-api-exporter
  namespace: pgo-monitoring
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app: "netapp-api-exporter"
