apiVersion: monitoring.coreos.com/v1
metadata:
  labels:
    k8s-app: prometheus
  name: prometheus
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: web
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: <PROMETHEUS_SERVICE_HOSTNAME>
  selector:
    matchLabels:
      prometheus: k8s-custom
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
spec:
  endpoints:
    - honorLabels: true
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: federated-monitor
  name: federated-prometheus
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    port: web
    path: /federate
    honorLabels: true
    params:
      'match[]': 
        - 'kubelet_volume_stats_available_bytes'
        - 'kube_pod_spec_volumes_persistentvolumeclaims_info'
    relabelings:
      - action: keep
        regex: prometheus-k8s-0
        sourceLabels:
          - __meta_kubernetes_pod_label_statefulset_kubernetes_io_pod_name
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: prometheus-k8s.openshift-monitoring.svc
  namespaceSelector:
    matchNames:
    - openshift-monitoring
  selector:
    matchLabels:
      prometheus: "k8s"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: cadvisor
  name: cadvisor
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      interval: 30s
      path: /metrics/cadvisor
      port: https-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: crunchy-collect
  name: crunchy-collect
spec:
  endpoints:
    - interval: 30s
      port: postgres-exporter
      relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_crunchy_collect]
        action: keep
        regex: 'true'
      - sourceLabels: [__meta_kubernetes_namespace]
        action: replace
        targetLabel: kubernetes_namespace
      - sourceLabels: [__meta_kubernetes_pod_name]
        regex: (^[^-]*).*
        targetLabel: instance
        replacement: '$1'
      - sourceLabels: [__meta_kubernetes_namespace,__meta_kubernetes_pod_label_name]
        targetLabel: job
        separator: ': '
        replacement: '$1$2'
      - targetLabel: exp_type
        replacement: 'pg'
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      vendor: crunchydata
