{
 "title": "PGBackrest",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pgnodes",
    "query": "query_result( up{ exp_type = 'pg' } )"
   }
  ]
 },
 "panels": [
  {
   "title": "Time Since Last Completed Backup (Any)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_incr_backup_time_since_completion_seconds{job=\"[[pgnodes]]\"}",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Backup Runtime (Any)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_runtime_backup_runtime_seconds{job=\"[[pgnodes]]\"}",
     "legendFormat": "{{stanza}}_{{backup_type}}"
    }
   ]
  },
  {
   "title": "Time Since Last Completed Backup (Full)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_full_backup_time_since_completion_seconds{job=\"[[pgnodes]]\"}",
     "legendFormat": "{{stanza}}"
    }
   ]
  },
  {
   "title": "Time Since Last Completed Backup (Full,Diff)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_diff_backup_time_since_completion_seconds{job=\"[[pgnodes]]\"}",
     "legendFormat": "{{stanza}}"
    }
   ]
  }
 ]
}